name: Test Colonel X

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Test README
        run: test -f DOES-NOT-EXIST.md 
